### ISSUE TITLE
unable to install the package

### ISSUE THREAD

**Issue by RoyMenczerVonage** [bolsote/isoduration#14]
When running `pip install isoduration==20.11.0` or `pip install isoduration`
I get the following error:

> Could not find a version that satisfies the requirement isoduration (from versions: )
> No matching distribution found for isoduration

This happens to me in multiple environments

**Comment by bolsote** [comment]
@RoyMenczerVonage I realise this is now closed, but I'm wondering, which version of Python were you targeting? By the looks of it you might be using an unsupported version. We require at least 3.7. Given 3.6 will get to its end of life date in a couple of months, we have no plans of supporting it.

**Comment by RoyMenczerVonage** [comment]
It was indeed python 3.6
